"use client";

import React, { createContext, useContext, useState } from 'react';

export type Language = 'EN' | 'BM' | 'ZH';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    EN: {
        // Navbar
        "home": "Home",
        "about": "About Us",
        "services": "Services",
        "dashboard": "Dashboard",
        "contact": "Contact",
        "nav_auth": "Get Started",
        "search_location": "Location",
        "select_area": "Select Area",
        "search_service": "Service Type",
        "select_service": "Select Service",
        "service_daycare": "Pet Daycare",
        "service_hostel": "Pet Hostel",
        "service_clinic": "Pet Clinic",
        "service_training": "Pet Training",
        "service_grooming_type": "Pet Grooming",

        // Hero Section
        "hero_badge": "THE ALL-IN-ONE PET SERVICE MARKETPLACE",
        "hero_title_1": "WELCOME TO",
        "hero_title_2": "GROOMSHINE",
        "hero_sub": "Search, compare, and book verified pet grooming, daycare, hostel, and clinic services by location, price, and trusted brand ratings.",
        "hero_cta": "Find Services",
        "hero_trusted": "VERIFIED PARTNERS",
        "hero_rated": "Top Rated Providers",
        "hero_tag_grooming": "GROOMING",
        "hero_tag_boarding": "HOSTEL",
        "hero_tag_spa": "CLINIC",

        // Benefits/About Section
        "about_badge": "Welcome to GroomShine",
        "about_title": "Your Trusted Partner for Every Pet Need",
        "about_desc": "GroomShine is an online pet service booking platform designed to seamlessly connect pet dog owners with trusted pet service providers. Our primary goal is to transform the stress of managing pet care into a simpler, and more positive experience.",
        "about_cta": "Browse Marketplace",
        "about_story": "Our Platform",
        "about_story_title": "Pet Services That Feel Like Family",
        "about_story_desc": "At GroomShine, we believe in transparency and excellence. Our platform empowers both service providers and pet owners to create a better world for our furry friends.",
        "about_grooming_includes": "Services We Offer:",
        "about_grooming_1": "Basic Grooming & Full Grooming",
        "about_grooming_2": "Dog Boarding & Daycare",
        "about_grooming_3": "Dog Training & Pet Taxi",
        "about_grooming_4": "Hydrotherapy / Swimming",
        "about_grooming_5": "Pet Funerals & Cremation",
        "about_grooming_6": "Professional Pet Photography",
        "about_grooming_7": "Canine Massage & Touch Therapy",
        "about_experience": "5+ Years",
        "about_experience_desc": "of Professional Grooming",
        "about_our_story": "OUR STORY",
        "about_heading": "Transforming Pet Care Into a Simpler Experience",
        "about_p1": "GroomShine is an online pet service booking platform designed to seamlessly connect pet dog owners with trusted pet service providers. Our primary goal is to transform the stress of managing pet care into a simpler, and more positive experience.",
        "about_p2": "At GroomShine, we are committed to setting the highest standards in pet care. Our journey began with a simple yet powerful idea — to create a platform where pet owners can easily schedule a wide range of pet care services with confidence and peace of mind. We strive to make pet care more accessible, reliable, and convenient for every pet parent.",
        "about_benefit_1": "Certified Professional Groomers",
        "about_benefit_2": "Cage-Free & Clean Environment",
        "about_benefit_3": "Gentle, Non-Aggressive Approach",
        "about_benefit_4": "Easy Online Booking",

        // Pet Collection Section
        "collection_title": "PARTNER SERVICES",
        "collection_desc": "Explore a wide range of services from our verified partners.",
        "collection_cat_spa": "LUXURY CAT SPA",
        "collection_dog_hotel": "PREMIUM DOG HOSTEL",
        "collection_grooming": "EXPERT GROOMING",
        "view_details": "Book Now",

        // How We Serve Section
        "serve_badge": "OUR NETWORK",
        "serve_title": "A Trusted Ecosystem for Your Pets",
        "serve_desc": "GroomShine provides a secure platform where you can find top-tier services near you. We check certificates and verification for every partner.",
        "serve_1": "Verified Service Providers",
        "serve_2": "Real-time Booking System",
        "serve_3": "Service Area Search",
        "serve_4": "Quality Assurance",

        // Testimonials Section
        "testimonials_badge": "WHAT PET OWNERS SAY",
        "testimonials_title": "Loved by Pet Parents Across Malaysia",
        "testimonials_desc": "Hear from our happy customers who found the perfect pet care through GroomShine.",

        // Pricing Section
        "pricing_badge": "TRANSPARENT PRICING",
        "pricing_title": "Choose Your Perfect Package",
        "pricing_desc": "Simple, honest pricing for every pet care need. No hidden fees.",
        "pricing_basic": "Basic Grooming",
        "pricing_full": "Full Package",
        "pricing_premium": "Premium Spa",
        "pricing_popular": "Most Popular",
        "pricing_from": "From",
        "pricing_per_session": "per session",
        "pricing_per_night": "per night",
        "pricing_book": "Book via WhatsApp",
        "pricing_feat_bath": "Bath & Blow Dry",
        "pricing_feat_nail": "Nail Trimming",
        "pricing_feat_ear": "Ear Cleaning",
        "pricing_feat_styling": "Breed Styling",
        "pricing_feat_teeth": "Teeth Brushing",
        "pricing_feat_deshed": "De-Shedding Treatment",
        "pricing_feat_spa": "Nano Bubble Spa",
        "pricing_feat_massage": "Relaxing Massage",
        "pricing_feat_mask": "Hydrating Fur Mask",
        "pricing_feat_perfume": "Premium Perfume",

        // FAQ Section
        "faq_badge": "FREQUENTLY ASKED QUESTIONS",
        "faq_title": "Got Questions? We've Got Answers",
        "faq_desc": "Everything you need to know about our services and platform.",
        "faq_q1": "How does GroomShine work?",
        "faq_a1": "GroomShine is a marketplace that connects pet owners with verified service providers. Simply search by area and service type, compare options, read reviews, and book your preferred provider directly through our platform.",
        "faq_q2": "Are all service providers verified?",
        "faq_a2": "Yes! Every partner on GroomShine goes through a thorough verification process. We check business licenses, certifications, facility standards, and customer reviews before approving any service provider.",
        "faq_q3": "What services are available on the platform?",
        "faq_a3": "We offer a wide range of pet services including professional grooming, cage-free boarding, nano bubble spa treatments, pet daycare, veterinary clinics, and pet training — all from verified providers.",
        "faq_q4": "How do I book a service?",
        "faq_a4": "You can book directly through our platform by selecting your preferred service and provider, choosing a date and time, and confirming your booking. You can also contact providers via WhatsApp for quick bookings.",
        "faq_q5": "Is cage-free boarding safe for my pet?",
        "faq_a5": "Absolutely! Our cage-free boarding partners maintain clean, supervised environments with 24/7 human presence. Pets are grouped by size and temperament to ensure everyone's comfort and safety.",
        "faq_q6": "What areas do you serve?",
        "faq_a6": "GroomShine currently serves all major areas in Malaysia including Kuala Lumpur, Selangor, Johor, Penang, and more. We're constantly expanding our network of verified partners across the country.",
        "faq_q7": "Can I become a service provider on GroomShine?",
        "faq_a7": "Yes! If you're a pet service business, you can register as a B2B partner on our platform. We'll verify your credentials and help you reach more pet owners in your area.",
        "faq_q8": "What if I'm not satisfied with a service?",
        "faq_a8": "Customer satisfaction is our priority. If you experience any issues, our support team will work with you and the service provider to resolve the matter. All verified partners are held to high quality standards.",

        // Contact Page
        "contact_badge": "GET IN TOUCH",
        "contact_title": "We'd Love to Hear From You",
        "contact_desc": "Have a question or want to book a service? Reach out to us and we'll get back to you as soon as possible.",
        "contact_name": "Your Name",
        "contact_email": "Email Address",
        "contact_phone": "Phone Number",
        "contact_service_interest": "Service Interest",
        "contact_select_service": "Select a service...",
        "contact_message": "Your Message",
        "contact_send": "Send Message",
        "contact_success_title": "Message Sent!",
        "contact_success_desc": "Thank you for reaching out. We'll get back to you within 24 hours.",
        "contact_info_title": "Contact Information",
        "contact_address": "Our Location",
        "contact_hours": "Opening Hours",
        "contact_hours_value": "Mon - Sun: 11:00 AM - 7:00 PM",
        "contact_whatsapp": "WhatsApp Us",

        // About Page
        "about_page_badge": "ABOUT GROOMSHINE",
        "about_page_title": "Building the Future of Pet Care in Malaysia",
        "about_page_desc": "From a small grooming shop in Cheras to Malaysia's growing pet services marketplace.",
        "about_mission_title": "Our Mission",
        "about_mission_desc": "To connect every pet owner in Malaysia with trusted, verified pet service providers through technology and transparency.",
        "about_vision_title": "Our Vision",
        "about_vision_desc": "To become Southeast Asia's leading pet services marketplace, where quality care is accessible to every pet family.",
        "about_team_badge": "MEET THE TEAM",
        "about_team_title": "The People Behind GroomShine",
        "about_values_title": "Our Core Values",
        "about_value_1_title": "Trust & Safety",
        "about_value_1_desc": "Every partner is verified and held to the highest standards of pet care.",
        "about_value_2_title": "Innovation",
        "about_value_2_desc": "Using technology to make pet care accessible and convenient for everyone.",
        "about_value_3_title": "Community",
        "about_value_3_desc": "Building a supportive network of pet lovers and service providers.",
        "about_value_4_title": "Excellence",
        "about_value_4_desc": "Constantly raising the bar for pet services quality across Malaysia.",
        "about_cta_title": "Join Our Growing Marketplace",
        "about_cta_desc": "Whether you're a pet owner looking for the best care, or a service provider wanting to grow your business — GroomShine is for you.",
        "about_cta_button": "Get Started Today",

        // Location Section
        "location_badge": "Visit Us",
        "location_title": "Find Us in Cheras",
        "location_desc": "We are conveniently located in Taman Maluri, just minutes away from downtown KL.",
        "location_address_title": "Location",
        "location_hours_title": "Opening Hours",
        "location_hours_value": "Monday - Sunday: 11:00 am - 07:00 pm",
        "location_contact_title": "Contact Us",
        "location_directions": "Get Directions",

        // Footer
        "footer_tagline": "The all-in-one pet service marketplace.",
        "footer_quick_links": "Quick Links",
        "footer_about": "About",
        "footer_training": "Services",
        "footer_grooming": "Partners",
        "footer_services_col": "Services",
        "footer_grooming_link": "Pet Grooming",
        "footer_boarding_link": "Pet Boarding",
        "footer_spa_link": "Nano Bubble Spa",
        "footer_browse_services": "Browse Services",
        "footer_dashboard": "Dashboard",
        "footer_for_business": "For Business",
        "footer_become_partner": "Become a Partner",
        "footer_partner_dashboard": "Partner Dashboard",
        "footer_connect": "Connect",
        "footer_subscribe": "Subscribe",
        "footer_email": "Email",
        "footer_rights": "ALL RIGHT RESERVED | GROOMSHINE 2026",
        "footer_back_top": "Back to Top",
        "footer_contact": "Contact",
        "footer_partner_signup": "Become a Partner",

        // Services Page
        "services_badge": "PRECISION & CARE",
        "services_hero_title": "LUXURY SERVICES FOR YOUR PET",
        "services_hero_desc": "Elevating the standard of pet care in Kuala Lumpur. Professional, empathetic, and dedicated to your pet's happiness.",
        "services_breadcrumb_home": "Home",
        "services_breadcrumb_services": "Services",
        "services_cta_title": "Not Sure Which Service Is Right?",
        "services_cta_desc": "Our team is happy to help you find the perfect care for your furry friend. Get in touch with us today!",
        "services_cta_button": "Contact Us",
        "service_grooming": "Pet Grooming",
        "service_grooming_desc": "Precision and care meet in our professional grooming suite. We don't just groom; we curate a stress-free experience tailored to your pet's specific needs.",
        "service_boarding": "Cage-Free Boarding",
        "service_boarding_desc": "Freedom is the heart of our boarding. No cages, no stress—just comfortable luxury with 24/7 human presence and unlimited playtime.",
        "service_spa": "Nano Bubble Spa",
        "service_spa_desc": "The ultimate skin detox. Our nano-bubble technology penetrates deep into the pores, removing toxins and soothing sensitive skin conditions.",
        "reserve_now": "Reserve Now",

        // Service Features
        "feat_styling": "Standard Breed Styling",
        "feat_bathing": "Medicated Bathing",
        "feat_nail": "Nail Dremeling",
        "feat_ear": "Ear Hygiene",
        "feat_facial": "Facial Scrub",
        "feat_deshed": "De-Shedding",
        "feat_private": "Private Sleeping Zones",
        "feat_social": "Social Interaction",
        "feat_supervision": "24/7 Supervision",
        "feat_meal": "Gourmet Meal Plans",
        "feat_photo": "Daily Photo Updates",
        "feat_climate": "Sanitized Climate",
        "feat_pore": "Pore Deep Cleaning",
        "feat_oxygen": "Skin Oxygenation",
        "feat_odor": "Odor Elimination",
        "feat_stress": "Stress Reduction",
        "feat_antibac": "Antibacterial Action",
        "feat_revital": "Revitalizing Finish",

        // Service Detail
        "service_detail_related": "Related Services",
        "service_detail_back": "Back to Services",

        // WhatsApp
        "whatsapp_chat": "Chat with us on WhatsApp",

        // Page Hero shared
        "page_hero_home": "Home"
    },
    BM: {
        // Navbar
        "home": "Laman Utama",
        "about": "Tentang GroomShine",
        "services": "Pasaran Perkhidmatan",
        "dashboard": "Papan Pemuka",
        "contact": "Hubungi",
        "nav_auth": "Mula Sekarang",
        "search_location": "Lokasi",
        "select_area": "Pilih Kawasan",
        "search_service": "Jenis Perkhidmatan",
        "select_service": "Pilih Perkhidmatan",
        "service_daycare": "Daycare Haiwan",
        "service_hostel": "Asrama Haiwan",
        "service_clinic": "Klinik Haiwan",
        "service_training": "Latihan Haiwan",
        "service_grooming_type": "Dandanan Haiwan",

        // Hero Section
        "hero_badge": "PASARAN PERKHIDMATAN HAIWAN SEGALANYA-DALAM-SATU",
        "hero_title_1": "SELAMAT DATANG KE",
        "hero_title_2": "GROOMSHINE",
        "hero_sub": "Cari, bandingkan, dan tempah perkhidmatan dandanan, asrama, dan klinik haiwan yang disahkan mengikut lokasi, harga, dan penilaian jenama yang dipercayai.",
        "hero_cta": "Cari Perkhidmatan",
        "hero_trusted": "RAKAN KONGSI DISAHKAN",
        "hero_rated": "Penyedia Penilaian Tertinggi",
        "hero_tag_grooming": "DANDANAN",
        "hero_tag_boarding": "ASRAMA",
        "hero_tag_spa": "KLINIK",

        // Benefits/About Section
        "about_badge": "Selamat Datang ke GroomShine",
        "about_title": "Rakan Dipercayai untuk Setiap Keperluan Haiwan",
        "about_desc": "GroomShine adalah pasaran komprehensif yang menghubungkan pemilik haiwan dengan penyedia perkhidmatan terbaik. Sama ada anda memerlukan dandanan profesional, asrama yang selesa, atau penjagaan klinik khusus, kami menjamin kualiti dan kepercayaan pada setiap langkah.",
        "about_cta": "Layari Pasaran",
        "about_story": "Platform Kami",
        "about_story_title": "Perkhidmatan Haiwan Yang Terasa Seperti Keluarga",
        "about_story_desc": "Di GroomShine, kami percaya pada ketelusan dan kecemerlangan. Platform kami memperkasakan penyedia perkhidmatan dan pemilik haiwan untuk mencipta dunia yang lebih baik untuk rakan berbulu kami.",
        "about_grooming_includes": "Perkhidmatan Yang Kami Tawarkan:",
        "about_grooming_1": "Dandanan Asas & Dandanan Penuh",
        "about_grooming_2": "Penginapan & Jagaan Harian Anjing",
        "about_grooming_3": "Latihan Anjing & Teksi Haiwan",
        "about_grooming_4": "Hidroterapi / Berenang",
        "about_grooming_5": "Pengebumian & Kremasi Haiwan",
        "about_grooming_6": "Fotografi Haiwan Profesional",
        "about_grooming_7": "Urutan Anjing & Terapi Sentuhan",
        "about_experience": "5+ Tahun",
        "about_experience_desc": "Dandanan Profesional",
        "about_our_story": "KISAH KAMI",
        "about_heading": "Mengubah Penjagaan Haiwan Menjadi Pengalaman Lebih Mudah",
        "about_p1": "GroomShine ialah platform tempahan perkhidmatan haiwan dalam talian yang direka untuk menghubungkan pemilik anjing dengan penyedia perkhidmatan haiwan yang dipercayai. Matlamat utama kami ialah mengubah tekanan menguruskan penjagaan haiwan menjadi pengalaman yang lebih mudah dan positif.",
        "about_p2": "Di GroomShine, kami komited untuk menetapkan standard tertinggi dalam penjagaan haiwan. Perjalanan kami bermula dengan idea yang mudah tetapi berkuasa — untuk mencipta platform di mana pemilik haiwan boleh menjadualkan pelbagai perkhidmatan penjagaan haiwan dengan keyakinan dan ketenangan fikiran.",
        "about_benefit_1": "Groomer Profesional Bertauliah",
        "about_benefit_2": "Persekitaran Tanpa Sangkar & Bersih",
        "about_benefit_3": "Pendekatan Lembut & Tidak Agresif",
        "about_benefit_4": "Tempahan Online Mudah",

        // Pet Collection Section
        "collection_title": "PERKHIDMATAN RAKAN KONGSI",
        "collection_desc": "Terokai pelbagai perkhidmatan daripada rakan kongsi kami yang disahkan.",
        "collection_cat_spa": "SPA KUCING MEWAH",
        "collection_dog_hotel": "ASRAMA ANJING PREMIUM",
        "collection_grooming": "DANDANAN PAKAR",
        "view_details": "Tempah Sekarang",

        // How We Serve Section
        "serve_badge": "RANGKAIAN KAMI",
        "serve_title": "Ekosistem Dipercayai Untuk Haiwan Anda",
        "serve_desc": "GroomShine menyediakan platform selamat di mana anda boleh mencari perkhidmatan berkualiti tinggi berhampiran anda. Kami memeriksa sijil dan pengesahan untuk setiap rakan kongsi.",
        "serve_1": "Penyedia Perkhidmatan Disahkan",
        "serve_2": "Sistem Tempahan Masa Nyata",
        "serve_3": "Carian Kawasan Perkhidmatan",
        "serve_4": "Jaminan Kualiti",

        // Testimonials Section
        "testimonials_badge": "APA KATA PEMILIK HAIWAN",
        "testimonials_title": "Disayangi Ibu Bapa Haiwan di Seluruh Malaysia",
        "testimonials_desc": "Dengar daripada pelanggan gembira kami yang menemui penjagaan haiwan yang sempurna melalui GroomShine.",

        // Pricing Section
        "pricing_badge": "HARGA TELUS",
        "pricing_title": "Pilih Pakej Sempurna Anda",
        "pricing_desc": "Harga mudah dan jujur untuk setiap keperluan penjagaan haiwan. Tiada caj tersembunyi.",
        "pricing_basic": "Dandanan Asas",
        "pricing_full": "Pakej Penuh",
        "pricing_premium": "Spa Premium",
        "pricing_popular": "Paling Popular",
        "pricing_from": "Dari",
        "pricing_per_session": "setiap sesi",
        "pricing_per_night": "setiap malam",
        "pricing_book": "Tempah melalui WhatsApp",
        "pricing_feat_bath": "Mandi & Keringkan",
        "pricing_feat_nail": "Potong Kuku",
        "pricing_feat_ear": "Bersihkan Telinga",
        "pricing_feat_styling": "Gaya Baka",
        "pricing_feat_teeth": "Gosok Gigi",
        "pricing_feat_deshed": "Rawatan De-Shedding",
        "pricing_feat_spa": "Spa Nano Bubble",
        "pricing_feat_massage": "Urutan Relaks",
        "pricing_feat_mask": "Masker Bulu Pelembap",
        "pricing_feat_perfume": "Minyak Wangi Premium",

        // FAQ Section
        "faq_badge": "SOALAN LAZIM",
        "faq_title": "Ada Soalan? Kami Ada Jawapan",
        "faq_desc": "Segala yang anda perlu tahu tentang perkhidmatan dan platform kami.",
        "faq_q1": "Bagaimana GroomShine berfungsi?",
        "faq_a1": "GroomShine adalah pasaran yang menghubungkan pemilik haiwan dengan penyedia perkhidmatan yang disahkan. Cari mengikut kawasan dan jenis perkhidmatan, bandingkan pilihan, baca ulasan, dan tempah penyedia pilihan anda terus melalui platform kami.",
        "faq_q2": "Adakah semua penyedia perkhidmatan disahkan?",
        "faq_a2": "Ya! Setiap rakan kongsi di GroomShine melalui proses pengesahan yang teliti. Kami memeriksa lesen perniagaan, sijil, standard kemudahan, dan ulasan pelanggan sebelum meluluskan mana-mana penyedia perkhidmatan.",
        "faq_q3": "Apakah perkhidmatan yang ada di platform?",
        "faq_a3": "Kami menawarkan pelbagai perkhidmatan haiwan termasuk dandanan profesional, penginapan tanpa sangkar, rawatan spa nano bubble, daycare haiwan, klinik veterinar, dan latihan haiwan — semuanya daripada penyedia yang disahkan.",
        "faq_q4": "Bagaimana saya boleh menempah perkhidmatan?",
        "faq_a4": "Anda boleh menempah terus melalui platform kami dengan memilih perkhidmatan dan penyedia pilihan anda, memilih tarikh dan masa, dan mengesahkan tempahan anda. Anda juga boleh menghubungi penyedia melalui WhatsApp.",
        "faq_q5": "Adakah penginapan tanpa sangkar selamat?",
        "faq_a5": "Sudah tentu! Rakan penginapan tanpa sangkar kami mengekalkan persekitaran yang bersih dan diselia dengan kehadiran manusia 24/7. Haiwan dikumpulkan mengikut saiz dan perangai.",
        "faq_q6": "Kawasan mana yang anda layani?",
        "faq_a6": "GroomShine kini melayani semua kawasan utama di Malaysia termasuk Kuala Lumpur, Selangor, Johor, Pulau Pinang, dan banyak lagi. Kami sentiasa mengembangkan rangkaian rakan kongsi kami.",
        "faq_q7": "Bolehkah saya menjadi penyedia perkhidmatan di GroomShine?",
        "faq_a7": "Ya! Jika anda perniagaan perkhidmatan haiwan, anda boleh mendaftar sebagai rakan kongsi B2B di platform kami. Kami akan mengesahkan kelayakan anda dan membantu anda menjangkau lebih ramai pemilik haiwan.",
        "faq_q8": "Apa jika saya tidak berpuas hati?",
        "faq_a8": "Kepuasan pelanggan adalah keutamaan kami. Jika anda mengalami sebarang masalah, pasukan sokongan kami akan bekerjasama dengan anda dan penyedia perkhidmatan untuk menyelesaikan perkara tersebut.",

        // Contact Page
        "contact_badge": "HUBUNGI KAMI",
        "contact_title": "Kami Ingin Mendengar Daripada Anda",
        "contact_desc": "Ada soalan atau ingin menempah perkhidmatan? Hubungi kami dan kami akan membalas secepat mungkin.",
        "contact_name": "Nama Anda",
        "contact_email": "Alamat Emel",
        "contact_phone": "Nombor Telefon",
        "contact_service_interest": "Perkhidmatan Diminati",
        "contact_select_service": "Pilih perkhidmatan...",
        "contact_message": "Mesej Anda",
        "contact_send": "Hantar Mesej",
        "contact_success_title": "Mesej Dihantar!",
        "contact_success_desc": "Terima kasih kerana menghubungi. Kami akan membalas dalam masa 24 jam.",
        "contact_info_title": "Maklumat Hubungan",
        "contact_address": "Lokasi Kami",
        "contact_hours": "Waktu Operasi",
        "contact_hours_value": "Isn - Ahd: 11:00 PG - 7:00 PTG",
        "contact_whatsapp": "WhatsApp Kami",

        // About Page
        "about_page_badge": "TENTANG GROOMSHINE",
        "about_page_title": "Membina Masa Depan Penjagaan Haiwan di Malaysia",
        "about_page_desc": "Dari kedai dandanan kecil di Cheras ke pasaran perkhidmatan haiwan Malaysia yang berkembang.",
        "about_mission_title": "Misi Kami",
        "about_mission_desc": "Menghubungkan setiap pemilik haiwan di Malaysia dengan penyedia perkhidmatan haiwan yang dipercayai dan disahkan melalui teknologi dan ketelusan.",
        "about_vision_title": "Visi Kami",
        "about_vision_desc": "Menjadi pasaran perkhidmatan haiwan terkemuka di Asia Tenggara, di mana penjagaan berkualiti boleh diakses oleh setiap keluarga haiwan.",
        "about_team_badge": "PASUKAN KAMI",
        "about_team_title": "Orang Di Sebalik GroomShine",
        "about_values_title": "Nilai Teras Kami",
        "about_value_1_title": "Kepercayaan & Keselamatan",
        "about_value_1_desc": "Setiap rakan kongsi disahkan dan dipegang pada standard penjagaan haiwan tertinggi.",
        "about_value_2_title": "Inovasi",
        "about_value_2_desc": "Menggunakan teknologi untuk menjadikan penjagaan haiwan mudah diakses dan selesa.",
        "about_value_3_title": "Komuniti",
        "about_value_3_desc": "Membina rangkaian sokongan pencinta haiwan dan penyedia perkhidmatan.",
        "about_value_4_title": "Kecemerlangan",
        "about_value_4_desc": "Sentiasa meningkatkan standard kualiti perkhidmatan haiwan di seluruh Malaysia.",
        "about_cta_title": "Sertai Pasaran Kami yang Berkembang",
        "about_cta_desc": "Sama ada anda pemilik haiwan yang mencari penjagaan terbaik, atau penyedia perkhidmatan yang ingin mengembangkan perniagaan — GroomShine untuk anda.",
        "about_cta_button": "Mula Hari Ini",

        // Location Section
        "location_badge": "Lawati Kami",
        "location_title": "Cari Kami di Cheras",
        "location_desc": "Kami terletak di Taman Maluri, hanya beberapa minit dari pusat bandar KL.",
        "location_address_title": "Lokasi",
        "location_hours_title": "Waktu Operasi",
        "location_hours_value": "Isnin - Ahad: 11:00 pg - 07:00 ptg",
        "location_contact_title": "Hubungi Kami",
        "location_directions": "Dapatkan Arah",

        // Footer
        "footer_tagline": "Pasaran perkhidmatan haiwan segalanya-dalam-satu.",
        "footer_quick_links": "Pautan Pantas",
        "footer_about": "Tentang",
        "footer_training": "Perkhidmatan",
        "footer_grooming": "Rakan Kongsi",
        "footer_services_col": "Perkhidmatan",
        "footer_grooming_link": "Dandanan Haiwan",
        "footer_boarding_link": "Penginapan Haiwan",
        "footer_spa_link": "Spa Nano Bubble",
        "footer_browse_services": "Layari Perkhidmatan",
        "footer_dashboard": "Papan Pemuka",
        "footer_for_business": "Untuk Perniagaan",
        "footer_become_partner": "Jadi Rakan Niaga",
        "footer_partner_dashboard": "Papan Pemuka Rakan Niaga",
        "footer_connect": "Hubungan",
        "footer_subscribe": "Langgan",
        "footer_email": "Emel",
        "footer_rights": "HAK CIPTA TERPELIHARA | GROOMSHINE 2026",
        "footer_back_top": "Kembali ke Atas",
        "footer_contact": "Hubungi",
        "footer_partner_signup": "Jadi Rakan Kongsi",

        // Services Page
        "services_badge": "KETEPATAN & PENJAGAAN",
        "services_hero_title": "PERKHIDMATAN MEWAH UNTUK HAIWAN ANDA",
        "services_hero_desc": "Meningkatkan standard penjagaan haiwan di Kuala Lumpur. Profesional, empati dan dedikasi untuk kebahagiaan haiwan anda.",
        "services_breadcrumb_home": "Laman Utama",
        "services_breadcrumb_services": "Perkhidmatan",
        "services_cta_title": "Tidak Pasti Perkhidmatan Mana?",
        "services_cta_desc": "Pasukan kami gembira membantu anda mencari penjagaan sempurna untuk rakan berbulu anda. Hubungi kami hari ini!",
        "services_cta_button": "Hubungi Kami",
        "service_grooming": "Grooming Haiwan",
        "service_grooming_desc": "Ketepatan dan penjagaan bertemu di suite grooming profesional kami. Kami bukan sekadar grooming; kami mencipta pengalaman tanpa tekanan yang disesuaikan dengan keperluan khusus haiwan anda.",
        "service_boarding": "Penginapan Tanpa Sangkar",
        "service_boarding_desc": "Kebebasan adalah inti penginapan kami. Tiada sangkar, tiada tekanan—hanya kemewahan selesa dengan kehadiran manusia 24/7 dan masa bermain tanpa had.",
        "service_spa": "Spa Nano Bubble",
        "service_spa_desc": "Detoks kulit terbaik. Teknologi nano-bubble kami menembusi jauh ke dalam liang, mengeluarkan toksin dan menenangkan keadaan kulit sensitif.",
        "reserve_now": "Tempah Sekarang",

        // Service Features
        "feat_styling": "Gaya Baka Standard",
        "feat_bathing": "Mandi Perubatan",
        "feat_nail": "Pengikiran Kuku",
        "feat_ear": "Kebersihan Telinga",
        "feat_facial": "Scrub Muka",
        "feat_deshed": "De-Shedding",
        "feat_private": "Zon Tidur Peribadi",
        "feat_social": "Interaksi Sosial",
        "feat_supervision": "Pengawasan 24/7",
        "feat_meal": "Pelan Makanan Gourmet",
        "feat_photo": "Kemas Kini Foto Harian",
        "feat_climate": "Iklim Bersih",
        "feat_pore": "Pembersihan Liang Dalam",
        "feat_oxygen": "Oksigenasi Kulit",
        "feat_odor": "Penyingkiran Bau",
        "feat_stress": "Pengurangan Tekanan",
        "feat_antibac": "Tindakan Antibakteria",
        "feat_revital": "Penyelesaian Revitalisasi",

        // Service Detail
        "service_detail_related": "Perkhidmatan Berkaitan",
        "service_detail_back": "Kembali ke Perkhidmatan",

        // WhatsApp
        "whatsapp_chat": "Sembang dengan kami di WhatsApp",

        // Page Hero shared
        "page_hero_home": "Laman Utama"
    },
    ZH: {
        // Navbar
        "home": "首页",
        "about": "关于 GroomShine",
        "services": "服务市场",
        "dashboard": "仪表板",
        "contact": "联系我们",
        "nav_auth": "开始使用",
        "search_location": "区域",
        "select_area": "选择区域",
        "search_service": "服务类型",
        "select_service": "选择服务",
        "service_daycare": "宠物日托",
        "service_hostel": "宠物寄养",
        "service_clinic": "宠物诊所",
        "service_training": "宠物训练",
        "service_grooming_type": "宠物美容",

        // Hero Section
        "hero_badge": "全方位宠物服务市场",
        "hero_title_1": "欢迎来到",
        "hero_title_2": "GROOMSHINE",
        "hero_sub": "按位置、价格和值得信赖的品牌搜索、比较并预订经过验证的宠物美容、日托、寄养和诊所服务。",
        "hero_cta": "寻找服务",
        "hero_trusted": "经过验证的合作伙伴",
        "hero_rated": "评分最高的服务商",
        "hero_tag_grooming": "宠物美容",
        "hero_tag_boarding": "宠物寄养",
        "hero_tag_spa": "宠物诊所",

        // Benefits/About Section
        "about_badge": "欢迎来到 GroomShine",
        "about_title": "您宠物每一个需求的可靠伙伴",
        "about_desc": "GroomShine 是一个连接宠物主人与最佳服务提供商的综合市场。无论您需要专业美容、舒适寄养还是专业诊所护理，我们都在每一步确保质量和信任。",
        "about_cta": "浏览市场",
        "about_story": "我们的平台",
        "about_story_title": "像家人一样的宠物服务",
        "about_story_desc": "在 GroomShine，我们相信透明和卓越。我们的平台既为服务提供商也为宠物主人赋能，为我们的毛茸茸朋友创造一个更好的世界。",
        "about_grooming_includes": "我们提供的服务：",
        "about_grooming_1": "基础美容和全套美容",
        "about_grooming_2": "狗狗寄养和日间托管",
        "about_grooming_3": "狗狗训练和宠物出租车",
        "about_grooming_4": "水疗 / 游泳",
        "about_grooming_5": "宠物殡葬与火化",
        "about_grooming_6": "专业宠物摄影",
        "about_grooming_7": "犬类按摩与触摸疗法",
        "about_experience": "5+ 年",
        "about_experience_desc": "专业美容经验",
        "about_our_story": "我们的故事",
        "about_heading": "将宠物护理转化为更简单的体验",
        "about_p1": "GroomShine 是一个在线宠物服务预订平台，旨在将宠物狗主人与值得信赖的宠物服务提供商无缝连接。我们的主要目标是将管理宠物护理的压力转化为更简单、更积极的体验。",
        "about_p2": "在 GroomShine，我们致力于在宠物护理方面设立最高标准。我们的旅程始于一个简单而强大的想法——创建一个平台，让宠物主人可以轻松安排各种宠物护理服务，拥有信心和安心。",
        "about_benefit_1": "认证专业美容师",
        "about_benefit_2": "无笼位清洁环境",
        "about_benefit_3": "温和、非攻击性方法",
        "about_benefit_4": "便捷在线预约",

        // Pet Collection Section
        "collection_title": "合作伙伴服务",
        "collection_desc": "探索我们经过验证的合作伙伴提供的广泛服务。",
        "collection_cat_spa": "豪华猫咪水疗",
        "collection_dog_hotel": "高端狗狗寄养",
        "collection_grooming": "专家宠物美容",
        "view_details": "立即预订",

        // How We Serve Section
        "serve_badge": "我们的网络",
        "serve_title": "为您宠物打造的值得信赖的生态系统",
        "serve_desc": "GroomShine 提供一个安全的平台，让您可以在附近找到顶级的服务。我们核查每个合作伙伴的证书和验证信息。",
        "serve_1": "经过验证的服务提供商",
        "serve_2": "实时预订系统",
        "serve_3": "服务区域搜索",
        "serve_4": "质量保证",

        // Testimonials Section
        "testimonials_badge": "宠物主人的评价",
        "testimonials_title": "深受马来西亚宠物家长喜爱",
        "testimonials_desc": "听听我们满意的客户如何通过 GroomShine 找到完美的宠物护理。",

        // Pricing Section
        "pricing_badge": "透明定价",
        "pricing_title": "选择您的完美套餐",
        "pricing_desc": "简单、诚实的价格满足每一个宠物护理需求。没有隐藏费用。",
        "pricing_basic": "基础美容",
        "pricing_full": "全套套餐",
        "pricing_premium": "高级水疗",
        "pricing_popular": "最受欢迎",
        "pricing_from": "起价",
        "pricing_per_session": "每次",
        "pricing_per_night": "每晚",
        "pricing_book": "通过 WhatsApp 预约",
        "pricing_feat_bath": "洗澡 & 吹干",
        "pricing_feat_nail": "修剪指甲",
        "pricing_feat_ear": "清洁耳朵",
        "pricing_feat_styling": "品种造型",
        "pricing_feat_teeth": "刷牙",
        "pricing_feat_deshed": "去毛处理",
        "pricing_feat_spa": "纳米气泡水疗",
        "pricing_feat_massage": "放松按摩",
        "pricing_feat_mask": "保湿毛发面膜",
        "pricing_feat_perfume": "高级香水",

        // FAQ Section
        "faq_badge": "常见问题",
        "faq_title": "有问题？我们有答案",
        "faq_desc": "关于我们的服务和平台，您需要了解的一切。",
        "faq_q1": "GroomShine 是如何运作的？",
        "faq_a1": "GroomShine 是一个连接宠物主人和经过验证的服务提供商的市场。只需按区域和服务类型搜索，比较选择，阅读评论，然后直接通过我们的平台预订您喜欢的服务商。",
        "faq_q2": "所有服务提供商都经过验证吗？",
        "faq_a2": "是的！GroomShine 上的每个合作伙伴都经过严格的验证过程。我们在批准任何服务提供商之前会检查营业执照、资质证书、设施标准和客户评价。",
        "faq_q3": "平台上有哪些服务？",
        "faq_a3": "我们提供广泛的宠物服务，包括专业美容、无笼位寄养、纳米气泡水疗、宠物日托、兽医诊所和宠物训练——全部来自经过验证的服务商。",
        "faq_q4": "如何预约服务？",
        "faq_a4": "您可以通过我们的平台直接预约，选择您喜欢的服务和服务商，选择日期和时间，确认预约即可。您也可以通过 WhatsApp 联系服务商快速预约。",
        "faq_q5": "无笼位寄养安全吗？",
        "faq_a5": "当然安全！我们的无笼位寄养合作伙伴维持清洁、有人监管的环境，24/7 有人值守。宠物按体型和性格分组，确保每位的舒适和安全。",
        "faq_q6": "你们服务哪些地区？",
        "faq_a6": "GroomShine 目前服务马来西亚所有主要地区，包括吉隆坡、雪兰莪、柔佛、槟城等。我们不断扩展全国的合作伙伴网络。",
        "faq_q7": "我可以成为 GroomShine 的服务提供商吗？",
        "faq_a7": "可以！如果您是宠物服务企业，可以在我们的平台上注册为 B2B 合作伙伴。我们将验证您的资质，帮助您触达更多您所在地区的宠物主人。",
        "faq_q8": "如果我对服务不满意怎么办？",
        "faq_a8": "客户满意是我们的首要任务。如果您遇到任何问题，我们的支持团队将与您和服务提供商合作解决。所有经过验证的合作伙伴都必须遵守高质量标准。",

        // Contact Page
        "contact_badge": "联系我们",
        "contact_title": "我们很乐意听到您的消息",
        "contact_desc": "有问题或想预约服务？联系我们，我们会尽快回复您。",
        "contact_name": "您的姓名",
        "contact_email": "电子邮箱",
        "contact_phone": "电话号码",
        "contact_service_interest": "感兴趣的服务",
        "contact_select_service": "选择服务...",
        "contact_message": "您的留言",
        "contact_send": "发送消息",
        "contact_success_title": "消息已发送！",
        "contact_success_desc": "感谢您的联系。我们将在 24 小时内回复您。",
        "contact_info_title": "联系信息",
        "contact_address": "我们的位置",
        "contact_hours": "营业时间",
        "contact_hours_value": "周一至周日：上午 11:00 - 下午 7:00",
        "contact_whatsapp": "WhatsApp 联系我们",

        // About Page
        "about_page_badge": "关于 GROOMSHINE",
        "about_page_title": "构建马来西亚宠物护理的未来",
        "about_page_desc": "从蕉赖的一家小美容店到马来西亚不断发展的宠物服务市场。",
        "about_mission_title": "我们的使命",
        "about_mission_desc": "通过技术和透明度，将马来西亚每位宠物主人与值得信赖、经过验证的宠物服务提供商连接起来。",
        "about_vision_title": "我们的愿景",
        "about_vision_desc": "成为东南亚领先的宠物服务市场，让每个宠物家庭都能获得优质护理。",
        "about_team_badge": "认识团队",
        "about_team_title": "GroomShine 背后的人们",
        "about_values_title": "我们的核心价值观",
        "about_value_1_title": "信任与安全",
        "about_value_1_desc": "每个合作伙伴都经过验证，并保持最高的宠物护理标准。",
        "about_value_2_title": "创新",
        "about_value_2_desc": "利用技术使宠物护理对每个人都便捷和方便。",
        "about_value_3_title": "社区",
        "about_value_3_desc": "建立宠物爱好者和服务提供商的支持性网络。",
        "about_value_4_title": "卓越",
        "about_value_4_desc": "不断提高马来西亚宠物服务质量标准。",
        "about_cta_title": "加入我们不断增长的市场",
        "about_cta_desc": "无论您是寻找最佳护理的宠物主人，还是想要发展业务的服务提供商——GroomShine 适合您。",
        "about_cta_button": "今天就开始",

        // Location Section
        "location_badge": "访问我们",
        "location_title": "在蕉赖找到我们",
        "location_desc": "我们位于 Taman Maluri，距离吉隆坡市中心仅几分钟路程。",
        "location_address_title": "位置",
        "location_hours_title": "营业时间",
        "location_hours_value": "周一至周日：上午 11:00 - 下午 7:00",
        "location_contact_title": "联系我们",
        "location_directions": "获取路线",

        // Footer
        "footer_tagline": "全方位宠物服务市场。",
        "footer_quick_links": "快速链接",
        "footer_about": "关于",
        "footer_training": "服务项目",
        "footer_grooming": "合作伙伴",
        "footer_services_col": "服务项目",
        "footer_grooming_link": "宠物美容",
        "footer_boarding_link": "宠物寄养",
        "footer_spa_link": "纳米气泡水疗",
        "footer_browse_services": "浏览服务",
        "footer_dashboard": "仪表板",
        "footer_for_business": "商业合作",
        "footer_become_partner": "成为合作伙伴",
        "footer_partner_dashboard": "合作伙伴仪表板",
        "footer_connect": "联系",
        "footer_subscribe": "订阅我们",
        "footer_email": "电子邮件",
        "footer_rights": "版权所有 | GROOMSHINE 2026",
        "footer_back_top": "回到顶部",
        "footer_contact": "联系我们",
        "footer_partner_signup": "成为合作伙伴",

        // Services Page
        "services_badge": "精准与关怀",
        "services_hero_title": "为您的宠物提供奢华服务",
        "services_hero_desc": "提升吉隆坡宠物护理标准。专业、同理心，致力于您宠物的幸福。",
        "services_breadcrumb_home": "首页",
        "services_breadcrumb_services": "服务",
        "services_cta_title": "不确定选择哪项服务？",
        "services_cta_desc": "我们的团队很乐意帮助您为毛茸茸的朋友找到完美的护理。今天就联系我们吧！",
        "services_cta_button": "联系我们",
        "service_grooming": "宠物美容",
        "service_grooming_desc": "精准与关怀在我们的专业美容套房中相遇。我们不仅仅是美容；我们根据您宠物的特定需求打造无压力体验。",
        "service_boarding": "无笼位寄养",
        "service_boarding_desc": "自由是我们寄养的核心。没有笼子，没有压力——只有舒适的奢华、24/7人员陪伴和无限的游戏时间。",
        "service_spa": "纳米气泡水疗",
        "service_spa_desc": "终极皮肤排毒。我们的纳米气泡技术深入毛孔，去除毒素，舒缓敏感皮肤问题。",
        "reserve_now": "立即预订",

        // Service Features
        "feat_styling": "标准品种造型",
        "feat_bathing": "药浴",
        "feat_nail": "指甲修剪",
        "feat_ear": "耳部卫生",
        "feat_facial": "面部磨砂",
        "feat_deshed": "去毛",
        "feat_private": "私人睡眠区",
        "feat_social": "社交互动",
        "feat_supervision": "24/7监督",
        "feat_meal": "美食计划",
        "feat_photo": "每日照片更新",
        "feat_climate": "消毒环境",
        "feat_pore": "深层毛孔清洁",
        "feat_oxygen": "皮肤充氧",
        "feat_odor": "消除异味",
        "feat_stress": "减轻压力",
        "feat_antibac": "抗菌作用",
        "feat_revital": "焕活效果",

        // Service Detail
        "service_detail_related": "相关服务",
        "service_detail_back": "返回服务",

        // WhatsApp
        "whatsapp_chat": "通过 WhatsApp 与我们聊天",

        // Page Hero shared
        "page_hero_home": "首页"
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('EN');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
